"""'add user memory tables'

Revision ID: 21591b024328
Revises: 6cb8ca68a78d
Create Date: 2026-05-04 16:10:52.501733

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21591b024328"
down_revision: str | None = "6cb8ca68a78d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_memory_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "RULE",
                "PREFERENCE",
                "USER_INFO",
                "NOTE",
                name="memory_section",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "POSSIBLE",
                "CONFIRMED",
                "ARCHIVED",
                name="memory_item_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_memory_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_memory_items_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_user_memory_items_user_section_status",
            ["user_id", "section", "status"],
            unique=False,
        )

    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("address_text", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    with op.batch_alter_table("user_memory_items", schema=None) as batch_op:
        batch_op.drop_index("ix_user_memory_items_user_section_status")
        batch_op.drop_index(batch_op.f("ix_user_memory_items_user_id"))

    op.drop_table("user_memory_items")
    # ### end Alembic commands ###
