"""'add locations table'

Revision ID: 6cb8ca68a78d
Revises: d3bda021c298
Create Date: 2026-05-01 00:17:39.967677

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cb8ca68a78d"
down_revision: str | None = "d3bda021c298"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CAFE",
                "RESTAURANT",
                "BAR",
                "PARK",
                "MUSEUM",
                "GALLERY",
                "ATTRACTION",
                "SHOP",
                "HOTEL",
                "ENTERTAINMENT",
                "OTHER",
                name="location_category",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "price_level",
            sa.Enum(
                "FREE", "LOW", "MEDIUM", "HIGH", name="price_level", native_enum=False, length=20
            ),
            nullable=True,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_locations_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locations_name"))
        batch_op.drop_index(batch_op.f("ix_locations_category"))

    op.drop_table("locations")
    # ### end Alembic commands ###
